openapi: "3.0.0"
info:
  title: "demo plugins app"
  version: "1.0.0"
  description: "programma di prova per implementare differenti plugins"
servers:
  - url: http://localhost:8080
tags:
  - name: Utente
  - name: Cosa
paths:
  /utente:
    get:
      tags:
        - "Utente"
      description: prende un utente
      operationId: getUtente
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: long
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtenteDTO'
    post:
      tags:
        - "Utente"
      summary: "registra un utente"
      description: "registra un utente nel database"
      operationId: "addUtente"
      requestBody:
        description: "object Utente per la aggiunta"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtenteDTO'
      responses:
        '201':
          description: "utente aggiunto con esito"
        '405':
          description: "input invalido"
    put:
      tags:
        - "Utente"
      summary: "aggiorna un utente"
      description: "aggiorna un utente nel database"
      operationId: "updateUtente"
      requestBody:
        description: "object Utente per la aggiunta"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtenteDTO'
      responses:
        '201':
          description: "utente aggiunto con esito"
        '405':
          description: "input invalido"
    delete:
      summary: rimuovi un utente
      operationId: deleteUtente
      parameters:
        - in: query
          name: utenteid
          required: true
          schema:
            type: long
      responses:
        200:
          description: OK
  /addcosatouser:
    post:
      tags:
        - "Utente"
      summary: "aggiunge una cosa al utente"
      operationId: "addCosaToUser"
      parameters:
        - in: query
          name: "utenteid"
          description: "id del utente"
          required: true
          schema:
            type: long
        - in: query
          name: "cosaid"
          description: "id della cosa"
          required: true
          schema:
            type: long
      responses:
        "200":
          description: "everything added ok"
  /cosa:
    post:
      tags:
        - "Cosa"
      summary: creare un oggetto cosa
      operationId: addCosa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CosaDTO'
      responses:
        "201":
          description: cosa creata con esito
    get:
      summary: presa di una cosa
      operationId: getCosa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: long
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CosaDTO'
    delete:
      tags:
        - "Cosa"
      summary: rimuovi una cosa
      operationId: deleteCosa
      parameters:
        - in: query
          name: cosaid
          required: true
          schema:
            type: long
      responses:
        200:
          description: OK
components:
  schemas:
    UtenteDTO:
      type: "object"
      required:
        - "name"
        - "lastname"
        - "username"
        - "password"
        - "email"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
          example: "mario"
        lastname:
          type: "string"
          example: "pontillo"
        username:
          type: "string"
          example: "bolters"
        password:
          type: "string"
          example: "1234"
        email:
          type: "string"
          example: "mario@gmail.com"
        cosaDTO:
          type: array
          items:
            $ref: '#/components/schemas/CosaDTO'
        completeName:
          type: "string"
        utilityTarget:
          type: "string"
    CosaDTO:
      type: object
      required:
        - cosaname
        - utility
        - materiale
      properties:
        idcosa:
          type: integer
        cosaname:
          type: string
        utility:
          type: string
        materiale:
          type: string



